# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GraduationPJ' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'AMap3DMap' #3D地图SDK
#   pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使用)
   pod 'AMapSearch' #搜索功能
   pod 'MJExtension'
   pod 'SocketRocket'
   pod 'AFNetworking'
   pod 'SDWebImage'
   pod 'Masonry'
  # Pods for GraduationPJ

end
